server:
  port: 8999

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/backend_v1?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
      username: root
      password: root
  web:
    resources:
      chain:
        cache: true
      add-mappings: false
  thymeleaf:
    cache: false
    prefix: classpath:/templates/app/
  mvc:
    throw-exception-if-no-handler-found: true

#  main:
#    banner-mode: off

mybatis-plus:
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    backend.v1: info

rsa:
  private-key-path: "${user.home}/backend/private_key.pem"
  public-key-path: "${user.home}/backend/public_key.pem"

jwt:
  secret: "your-256-bit-secret-key-base64-encoded"
  expiration: 86400000      # 24小时
  refresh-expiration: 604800000  # 7天